name: sprintf
version: 3.0.2
authors:
- Richard Eames <dartsprintf@naddiseo.ca>
- Michael Maroszek <mm@ip-symcon.de>
description: Dart implementation of sprintf
homepage: https://github.com/Naddiseo/dart-sprintf
dependencies:
  intl: any
dev_dependencies:
  test: any
