name: sprintf
version: 4.0.0
authors:
- Richard Eames <dartsprintf@naddiseo.ca>
- Michael Maroszek <mm@ip-symcon.de>
description: Dart implementation of sprintf
homepage: https://github.com/Naddiseo/dart-sprintf
dependencies:
  intl: any
environment:
  sdk: '<3.0.0'
dev_dependencies:
  test: any
